name: Sprout
options:
  bundleIdPrefix: com.shimondeitel
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "4"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Sprout:
    type: application
    platform: iOS
    sources:
      - path: Sprout
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.sprout
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Sprout/Info.plist
        CODE_SIGN_ENTITLEMENTS: Sprout/Sprout.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  SproutTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: SproutTests
      - path: Sprout.storekit
    dependencies:
      - target: Sprout
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.sprout.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  SproutUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: SproutUITests
    dependencies:
      - target: Sprout
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.sprout.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Sprout:
    build:
      targets:
        Sprout: all
        SproutTests: [test]
        SproutUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Sprout.storekit
    test:
      config: Debug
      storeKitConfiguration: Sprout.storekit
      targets:
        - SproutTests
        - SproutUITests
    archive:
      config: Release
